apiVersion: apps/v1
kind: Deployment
metadata:
  name: threat-api
spec:
  replicas: 3    
  selector:
    matchLabels:
      app: threat-api
      tier: backend
  template:
    metadata:
      labels:
        app: threat-api
        tier: backend
    spec:
      containers:
      - name: service-b
        image: danielzemtsovski/threat-api:v1
        ports:
        - containerPort: 8000
        env:
        - name: MONGO_HOST 
          value: "127.0.0.1"
        - name: MONGO_PORT 
          value: "27017"
        - name: MONGO_USERNAME
          value: "admin"
        - name: MONGO_PASSWORD 
          value: "secretpass"
        - name: MONGO_DB 
          value: "threat_db"
        - name: MONGO_AUTH_SOURCE 
          value: "admin"